SET SERVEROUTPUT ON
DECLARE 
    X NUMBER NOT NULL :=30;
    Z NUMBER NOT NULL :=40;
    NOMBRE VARCHAR(50):='GUILLERMO';
    EDAD NUMBER:=20;
    FECHA_NAC DATE:='30-03-2003';
BEGIN
    
    DBMS_OUTPUT.PUT_LINE(X+Z);
    DBMS_OUTPUT.PUT_LINE(NOMBRE||' '||EDAD||' '||FECHA_NAC);

    
END;