CREATE OR REPLACE TRIGGER TR1_REGION 
BEFORE INSERT OR UPDATE OF REGION_NAME OR DELETE
ON REGIONS BEGIN
    IF user <> 'HR' THEN
        raise_application_error(-20000, 'SOLO HR PUEDE TRABAJAR EN REGIONS');
    END IF;
END